checkpoint_path: ../train/training-output/checkpoint/ddf570a0-ea8f-4c25-b9ff-0c5077ef1af7/inference-last.ckpt
lead_time: 240

date: 2022-01-03T00

start_date: 2022-01-03T12
end_date: 2022-01-14T12
freq: 12h

input_dataset_kwargs: ../data/replay.zarr

output_path: inference_files
